FROM springcloud/spring-cloud-dataflow-server:${DATAFLOW_VERSION:-2.11.3-SNAPSHOT}${BP_JVM_VERSION:-}

COPY /tasks/config-batch-3.4.1.jar /Users/nazarii.tkachuk/IdeaProjects/Sombra/tasks/config-batch-3.4.1.jar

USER root